kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ts-cluster
nodes:
  # The Control Plane (Kubernetes Brain)
  - role: control-plane

  # ── CPU-Optimised nodes (2 CPUs, 1 GB RAM each) ──
  - role: worker
    labels:
      node-type: CPU_OPT
      ts.capacity/cpu: "2.0"
      ts.capacity/memory: "1024"
      ts.capacity/io: "100"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: ts-node-cpu-1
    extraMounts:
      - hostPath: /tmp/ts-shared-data
        containerPath: /ts-data

  - role: worker
    labels:
      node-type: CPU_OPT
      ts.capacity/cpu: "2.0"
      ts.capacity/memory: "1024"
      ts.capacity/io: "100"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: ts-node-cpu-2
    extraMounts:
      - hostPath: /tmp/ts-shared-data
        containerPath: /ts-data

  # ── Memory-Optimised nodes (1 CPU, 2 GB RAM each) ──
  - role: worker
    labels:
      node-type: MEM_OPT
      ts.capacity/cpu: "1.0"
      ts.capacity/memory: "2048"
      ts.capacity/io: "100"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: ts-node-mem-1
    extraMounts:
      - hostPath: /tmp/ts-shared-data
        containerPath: /ts-data

  - role: worker
    labels:
      node-type: MEM_OPT
      ts.capacity/cpu: "1.0"
      ts.capacity/memory: "2048"
      ts.capacity/io: "100"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: ts-node-mem-2
    extraMounts:
      - hostPath: /tmp/ts-shared-data
        containerPath: /ts-data

  # ── IO-Optimised nodes (1 CPU, 1 GB RAM each) ──
  - role: worker
    labels:
      node-type: IO_OPT
      ts.capacity/cpu: "1.0"
      ts.capacity/memory: "1024"
      ts.capacity/io: "1000"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: ts-node-io-1
    extraMounts:
      - hostPath: /tmp/ts-shared-data
        containerPath: /ts-data

  - role: worker
    labels:
      node-type: IO_OPT
      ts.capacity/cpu: "1.0"
      ts.capacity/memory: "1024"
      ts.capacity/io: "1000"
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: ts-node-io-2
    extraMounts:
      - hostPath: /tmp/ts-shared-data
        containerPath: /ts-data