import os
import json
from abc import ABC, abstractmethod
from typing import Dict, Any, List
from models.workload import WorkflowInstance

# --- 1. The Abstract Interface ---

class DataExchangeManager(ABC):
    """
    Handles the passing of data and artifact references between temporally decoupled tasks.
    """

    @abstractmethod
    def save_small_output(self, wf_instance_id: str, task_instance_id: str, data: Dict[str, Any]):
        """Saves small JSON/dictionary data generated by a task."""
        pass

    @abstractmethod
    def get_inputs_for_task(self, wf_instance_id: str, task_id: str, required_fields: List[str]) -> Dict[str, Any]:
        """Retrieves the required data fields from parent tasks."""
        pass

    @abstractmethod
    def provision_shared_workspace(self, wf_instance_id: str) -> str:
        """Defines and creates the shared storage path for large artifacts."""
        pass


# --- 2. The Local Disk (File Store) Implementation ---

class FileStoreDataManager(DataExchangeManager):
    def __init__(self, base_dir: str = "/tmp/thesis_data_store"):
        """
        Initializes the local disk manager. All workflow data lives under base_dir.
        """
        self.base_dir = base_dir
        os.makedirs(self.base_dir, exist_ok=True)

    def _get_wf_dir(self, wf_instance_id: str) -> str:
        """Helper to ensure the workflow instance directory exists."""
        wf_dir = os.path.join(self.base_dir, wf_instance_id)
        os.makedirs(wf_dir, exist_ok=True)
        return wf_dir

    def save_small_output(self, wf_instance_id: str, task_instance_id: str, data: Dict[str, Any]):
        """
        For every key (field name) in the data dictionary, it saves the value
        into a JSON file named {key}.json inside the workflow's directory.
        """
        wf_dir = self._get_wf_dir(wf_instance_id)
        
        for field_name, value in data.items():
            file_path = os.path.join(wf_dir, f"{field_name}.json")
            
            # Write the data to the disk
            with open(file_path, 'w') as f:
                json.dump(value, f)
                
            print(f"[FILE STORE] Task '{task_instance_id}' saved artifact '{field_name}' to {file_path}")

    def get_inputs_for_task(self, wf_instance_id: str, task_id: str, required_fields: List[str]) -> Dict[str, Any]:
        """
        Reads the requested field names from the disk and packages them into a dictionary
        to inject into the starting task.
        """
        wf_dir = self._get_wf_dir(wf_instance_id)
        inputs = {}
        
        if not required_fields:
            return inputs

        for field_name in required_fields:
            file_path = os.path.join(wf_dir, f"{field_name}.json")
            
            if os.path.exists(file_path):
                with open(file_path, 'r') as f:
                    inputs[field_name] = json.load(f)
            else:
                print(f"[FILE STORE WARNING] Task '{task_id}' requested '{field_name}', but {file_path} is missing!")
                inputs[field_name] = None
                
        return inputs

    def provision_shared_workspace(self, wf_instance_id: str) -> str:
        """
        Creates a dedicated 'shared_volume' folder for large files (Logic 1).
        """
        wf_dir = self._get_wf_dir(wf_instance_id)
        shared_workspace = os.path.join(wf_dir, "shared_volume")
        os.makedirs(shared_workspace, exist_ok=True)
        
        print(f"[FILE STORE] Provisioned shared workspace at {shared_workspace}")
        return shared_workspace