from enum import Enum, auto

class NodeType(Enum):
    CPU_OPT = auto()
    MEM_OPT = auto()
    IO_OPT = auto()
    GENERAL = auto()

class TaskClass(Enum):
    CPU_BOUND = auto()
    MEMORY_BOUND = auto()
    IO_BOUND = auto()

class WorkflowClass(Enum):
    REAL_TIME = auto()
    BATCH = auto()

# Using int allows for easy > or < comparisons in your priority queues later
class PriorityClass(int, Enum):
    LOW = 1
    NORMAL = 2
    HIGH = 3
    CRITICAL = 4

class TaskState(Enum):
    WAITING = auto()   # Waiting on DAG dependencies
    READY = auto()     # Dependencies met, waiting for scheduler
    SCHEDULED = auto() # Node assigned, waiting to start
    RUNNING = auto()   # Actively executing
    FINISHED = auto()  # Completed successfully
    FAILED = auto()

class WorkflowState(Enum):
    QUEUED = auto()    # Waiting for admission control
    ADMITTED = auto()  # Admitted to the system, tasks are resolving
    RUNNING = auto()   # At least one task is running
    FINISHED = auto()
    FAILED = auto()

class StartupState(Enum):
    WARM = auto()
    COLD = auto()
    UNKNOWN = auto()

class DependencyType(Enum):
    EXECUTION = auto()  # Control dependency: runs after parent finishes. No data shared.
    DATA = auto()       # Data dependency: requires an output generated by parent.